version: '3.3'

services:
    db:
        image: mariadb
        restart: always
        ports:
            - "3506:3306"
        environment:
            MYSQL_ROOT_PASSWORD: PepitoElDeLosPalotes
            MYSQL_USER: dra
            MYSQL_PASSWORD: pass123
            MYSQL_DATABASE: artifact
    
    jar:
        build: jar
        restart: always
        depends_on:
        - "db"
        ports:
            - "8084:8084"